### ISSUE TITLE
Thanks for the excellent http://emberigniter.com/fit-any-backend-into-ember-custom-adapters-serializers/ article!

### ISSUE THREAD

**Issue by ryrych** [frank06/ember-github-adapter#1]
I've read all your articles on emberigniter and they helped me to understand
some concepts better. All the best!

**Comment by ryrych** [comment]
![screen shot 2015-11-29 at 15 04 46](https://cloud.githubusercontent.com/assets/278637/11457526/8d3a168a-96ab-11e5-9617-9585d79014da.png)

It took me some time to send it via API, but it was worth it :)

By the way, [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop) is a handy tool to play, test with APIs. I used it to test creating issue [here](https://github.com/ryrych/ryrych.github.io/issues) so that this issue could be sent via Ember app. ;)

Thanks!

**Comment by frank06** [comment]
Hey Wojtek, love what you did! It's great!

And you're very welcome.

I definitely have Postman installed :) Indispensable tool.

**Comment by ryrych** [comment]
Thanks! A few days ago I pushed the changes. https://github.com/ryrych/emberigniter-github-examples
All the best!

**Comment by frank06** [comment]
Awesome!
